export const INITIAL_AUTH_STATE = {
    userStatus: 'No information',
    phoneNumber: 'phone number',
    ownerId: 'No information',
    email: 'No information',
    fullName: 'user',
    country: 'country',
    avatar: 'https://res.cloudinary.com/dzh01qrmx/image/upload/v1729506585/default-avatar_vxyg1c.png',
    transactions: [],
    friends: [],
    favorite_friends: [],
    address: 'No information',
    objectId: 'No information',
    virtualCard: {
        number: '0000 0000 0000 0000',
        expiration: '00/00',
        cvv: '000',
        balance: 0,
        issuer: 0,
        brand: 'No information',
        objectId: 'No information',
        created: 'information',
    },
};
