export * from './footer/Footer'
export * from './header/Header'
export * from './home/Home'
export * from './register/Register'
export * from './home/assets/login/Login'
export * from './home/assets/about/About'