export * from './Footer/Footer'
export * from './Header/Header'
export * from './home/Home'
export * from './register/Register'
export * from './dashboard/Dashboard'
export * from './home/assets/login/Login'
export * from './home/assets/about/About'